// 自動生成。手で編集しない（scripts/gen-airlines.mjs で再生成）。
// 出典: Wikidata（CC0）。運航中で IATA コードを持つ航空会社。
// 並びはサイトリンク数の降順＝知名度順で、検索の同点時の優先順位を兼ねる。
// [iata, icao, 英語名, 日本語名（英語名と同じなら null）]
export type AirlineRow = readonly [string, string | null, string, string | null];

export const AIRLINES: readonly AirlineRow[] = [
  ["LH", "DLH", "Lufthansa", "ルフトハンザドイツ航空"],
  ["TK", "THY", "Turkish Airlines", "ターキッシュ エアラインズ"],
  ["AF", "AFR", "Air France", "エールフランス"],
  ["BA", "BAW", "British Airways", "ブリティッシュ・エアウェイズ"],
  ["VJ", "VJC", "VietJet Air", "ベトジェットエア"],
  ["UA", "UAL", "United Airlines", "ユナイテッド航空"],
  ["KL", "KLM", "KLM", "KLMオランダ航空"],
  ["FR", "RYR", "Ryanair", "ライアンエアー"],
  ["SU", "AFL", "Aeroflot", "アエロフロート・ロシア航空"],
  ["EK", "UAE", "Emirates", "エミレーツ航空"],
  ["DL", "DAL", "Delta Air Lines", "デルタ航空"],
  ["DY", "NAX", "Norwegian Air Shuttle", "ノルウェー・エアシャトル"],
  ["RR", "RFR", "Royal Air Force", "イギリス空軍"],
  ["AA", "AAL", "American Airlines", "アメリカン航空"],
  ["QF", "QFA", "Qantas Airways", "カンタス航空"],
  ["QH", "BAV", "Bamboo Airways", "バンブー・エアウェイズ"],
  ["AC", "ACA", "Air Canada", "エア・カナダ"],
  ["MH", "MAS", "Malaysia Airlines", "マレーシア航空"],
  ["OS", "AUA", "Austrian Airlines", "オーストリア航空"],
  ["QR", "QTR", "Qatar Airways", "カタール航空"],
  ["SQ", "SIA", "Singapore Airlines", "シンガポール航空"],
  ["AI", "AIC", "Air India", "エア・インディア"],
  ["EY", "ETD", "Etihad Airways", "エティハド航空"],
  ["IB", "IBE", "Iberia", "イベリア航空"],
  ["SK", "SAS", "Scandinavian Airlines", "スカンジナビア航空"],
  ["TG", "THA", "Thai Airways", "タイ国際航空"],
  ["U2", "EZY", "easyJet", "イージージェット"],
  ["LX", "SWR", "Swiss International Air Lines", "スイスインターナショナルエアラインズ"],
  ["JL", "JAL", "Japan Airlines", "日本航空"],
  ["VN", "HVN", "Vietnam Airlines", "ベトナム航空"],
  ["2A", null, "Deutsche Bahn", "ドイツ鉄道"],
  ["CA", "CCA", "Air China", "中国国際航空"],
  ["AY", "FIN", "Finnair", "フィンランド航空"],
  ["KE", "KAL", "大韓航空", "大韓航空"],
  ["OK", "CSA", "Czech Airlines", "チェコ航空"],
  ["LO", "LOT", "LOT Polish Airlines", "LOTポーランド航空"],
  ["NH", "ANA", "All Nippon Airways", "全日本空輸"],
  ["CX", "CPA", "Cathay Pacific", "キャセイパシフィック航空"],
  ["NZ", "ANZ", "Air New Zealand", "ニュージーランド航空"],
  ["MU", "CES", "China Eastern Airlines", "中国東方航空"],
  ["VS", "VIR", "Virgin Atlantic", "ヴァージン・アトランティック航空"],
  ["WN", "SWA", "Southwest Airlines", "サウスウエスト航空"],
  ["SA", "SAA", "South African Airways", "南アフリカ航空"],
  ["ET", "ETH", "Ethiopian Airlines", "エチオピア航空"],
  ["EI", "EIN", "Aer Lingus", "エアリンガス"],
  ["W6", "WZZ", "Wizz Air", "ウィズエアー"],
  ["MS", "MSR", "EgyptAir", "エジプト航空"],
  ["SN", "BEL", "Brussels Airlines", "ブリュッセル航空"],
  ["BT", "BTI", "AirBaltic", "エア・バルティック"],
  ["2V", null, "アムトラック", "アムトラック"],
  ["A3", "AEE", "Aegean Airlines", "エーゲ航空"],
  ["TP", "TAP", "TAP Air Portugal", "TAPポルトガル航空"],
  ["J2", "AHY", "Azerbaijan Airlines", "アゼルバイジャン航空"],
  ["CZ", "CSN", "China Southern Airlines", "中国南方航空"],
  ["CI", "CAL", "China Airlines", "チャイナエアライン"],
  ["OZ", "AAR", "Asiana Airlines", "アシアナ航空"],
  ["AK", "AXM", "AirAsia", "エアアジア"],
  ["AS", "ASA", "Alaska Airlines", "アラスカ航空"],
  ["LY", "ELY", "EL AL Israel Airlines Ltd.", "エル・アル航空"],
  ["OU", "CTN", "Croatia Airlines", "クロアチア航空"],
  ["KQ", "KQA", "Kenya Airways", "ケニア航空"],
  ["AV", "AVA", "Avianca", "アビアンカ航空"],
  ["ON", "RON", "Nauru Airlines", "アワー航空"],
  ["PK", "PIA", "Pakistan International Airlines", "パキスタン国際航空"],
  ["6E", "IGO", "IndiGo", null],
  ["GA", "GIA", "Garuda Indonesia", "ガルーダ・インドネシア航空"],
  ["B2", "BRU", "Belavia", "ベラヴィア"],
  ["VY", "VLG", "Vueling", "ブエリング航空"],
  ["UL", "ALK", "SriLankan Airlines", "スリランカ航空"],
  ["JU", "ASL", "Air Serbia", "エア・セルビア"],
  ["FB", "LZB", "ブルガリア航空", "ブルガリア航空"],
  ["PR", "PAL", "Philippine Airlines", "フィリピン航空"],
  ["S7", "SBI", "S7航空", "S7航空"],
  ["FI", "ICE", "Icelandair", "アイスランド航空"],
  ["RO", "ROT", "タロム航空", "タロム航空"],
  ["FZ", "FDB", "flydubai", "フライドバイ"],
  ["SV", "SVA", "Saudia", "サウディア"],
  ["KC", "KZR", "Air Astana", "エア・アスタナ"],
  ["PC", "PGT", "Pegasus Airlines", "ペガサス航空"],
  ["UX", "AEA", "Air Europa", "エア・ヨーロッパ"],
  ["B6", "JBU", "JetBlue Airways", "ジェットブルー航空"],
  ["BR", "EVA", "EVA Air", "エバー航空"],
  ["RJ", "RJA", "Royal Jordanian", "ロイヤル・ヨルダン航空"],
  ["EW", "EWG", "Eurowings", "ユーロウイングス"],
  ["JS", "KOR", "Air Koryo", "高麗航空"],
  ["JT", "LNI", "Lion Air", "ライオン・エア"],
  ["IR", "IRA", "イラン航空", "イラン航空"],
  ["AM", "AMX", "Aeroméxico", "アエロメヒコ航空"],
  ["WY", "OMA", "Oman Air", "オマーン・エア"],
  ["HY", "UZB", "Uzbekistan Airways", "ウズベキスタン航空"],
  ["MK", "MAU", "Air Mauritius", "モーリシャス航空"],
  ["AR", "ARG", "アルゼンチン航空", "アルゼンチン航空"],
  ["KU", "KAC", "Kuwait Airways", "クウェート航空"],
  ["G9", "ABY", "Air Arabia", "エア・アラビア"],
  ["CM", "CMP", "Copa Airlines", "コパ航空"],
  ["TS", "TSC", "Air Transat", "エア・トランザット"],
  ["GF", "GFA", "Gulf Air", "ガルフ・エア"],
  ["ME", "MEA", "Middle East Airlines - Air Liban", "ミドル・イースト航空"],
  ["LA", "LAN", "LATAM Airlines", "ラタム・チリ"],
  ["F9", "FFT", "Frontier Airlines", "フロンティア航空"],
  ["T5", "TUA", "Turkmenistan Airlines", "トルクメニスタン航空"],
  ["HA", "HAL", "Hawaiian Airlines", "ハワイアン航空"],
  ["VA", "VOZ", "Virgin Australia", "ヴァージン・オーストラリア"],
  ["IZ", "AIZ", "Arkia", "アルキア・イスラエル航空"],
  ["AT", "RAM", "Royal Air Maroc", "ロイヤル・エア・モロッコ"],
  ["IX", "AXB", "Air India Express", "エア・インディア・エクスプレス"],
  ["G8", "GOW", "Go First", "GoAir"],
  ["AZ", "ITY", "ITA Airways", "ITA航空"],
  ["WS", "WJA", "WestJet", "ウエストジェット航空"],
  ["AH", "DAH", "Air Algérie", "アルジェリア航空"],
  ["GL", "GRL", "Air Greenland", "エア・グリーンランド"],
  ["DE", "CFG", "Condor Flugdienst", "コンドル航空"],
  ["FV", "SDM", "Rossiya", "ロシア航空"],
  ["A9", "TGZ", "Georgian Airways", "ジョージアン・エアウェイズ"],
  ["BI", "RBA", "Royal Brunei Airlines", "ロイヤルブルネイ航空"],
  ["JQ", "JST", "Jetstar Airways", "ジェットスター航空"],
  ["RC", "FLI", "Atlantic Airways", "アトランティック・エアウェイズ"],
  ["RA", "RNA", "Nepal Airlines", "ネパール航空"],
  ["BG", "BBC", "ビーマン・バングラデシュ航空", "ビーマン・バングラデシュ航空"],
  ["FM", "CSH", "Shanghai Airlines", "上海航空"],
  ["HV", "TRA", "Transavia", "トランサヴィア"],
  ["SG", "SEJ", "SpiceJet", "スパイスジェット"],
  ["FJ", "FJI", "Fiji Airways", "フィジー・エアウェイズ"],
  ["IA", "IAW", "Iraqi Airways", "イラク航空"],
  ["UU", "REU", "Air Austral", "エール・オーストラル"],
  ["XQ", "SXS", "SunExpress", "サンエクスプレス"],
  ["LG", "LGL", "Luxair", "ルクスエア"],
  ["JJ", "TAM", "LATAM Brasil", "ラタム・ブラジル"],
  ["TU", "TAR", "Tunisair", "チュニスエア"],
  ["8U", "AAW", "アフリキヤ航空", "アフリキヤ航空"],
  ["U6", "SVR", "Ural Airlines", "ウラル航空"],
  ["WK", "EDW", "Edelweiss Air", "エーデルワイス航空"],
  ["PG", "BKP", "Bangkok Airways", "バンコク・エアウェイズ"],
  ["LS", "EXS", "Jet2.com", null],
  ["HU", "CHH", "Hainan Airlines", "海南航空"],
  ["YT", "NYT", "Yeti Airlines", "イエティ航空"],
  ["X9", "NVD", "Avion Express", null],
  ["HX", "CRK", "Hong Kong Airlines", "香港航空"],
  ["QS", "TVS", "Smartwings", "トラベル･サービス"],
  ["EN", "DLA", "Air Dolomiti", "エア・ドロミティ"],
  ["PA", "ABQ", "airblue", "エアブルー"],
  ["G4", "AAY", "Allegiant Air", "アレジアント・エア"],
  ["QV", "LAO", "Lao Airlines", "ラオス国営航空"],
  ["MD", "MGY", "Air Madagascar", "マダガスカル航空"],
  ["DD", "NOK", "Nok Air", "ノックエア"],
  ["AD", "AZU", "アズールブラジル航空", "アズールブラジル航空"],
  ["U4", "BHA", "Buddha Air", "ブッダ・エアー"],
  ["KB", "DRK", "Drukair", "ドゥルク航空"],
  ["HM", "SEY", "Air Seychelles", "セーシェル航空"],
  ["ZH", "CSZ", "Shenzhen Airlines", "深圳航空"],
  ["5J", "CEB", "Cebu Pacific", "セブパシフィック航空"],
  ["UT", "UTA", "UTair Aviation", "UTエアー"],
  ["CV", "CLX", "Cargolux", "カーゴルックス航空"],
  ["YW", "ANE", "Air Nostrum", "エア・ノストラム"],
  ["UM", "AZW", "Air Zimbabwe", "エア・ジンバブエ"],
  ["W3", "ARA", "Arik Air", "アリクエア"],
  ["SM", "MSC", "Air Cairo", "カイロ航空"],
  ["MP", "MPH", "Martinair", "マーティンエアー"],
  ["TC", "ATC", "Air Tanzania", "エア・タンザニア"],
  ["BL", "PIC", "Pacific Airlines", "パシフィック航空"],
  ["WA", "KLC", "KLM Cityhopper", "KLMシティホッパー"],
  ["J9", "JZR", "Jazeera Airways", "ジャジーラ航空"],
  ["MF", "CXA", "Xiamen Airlines", "厦門航空"],
  ["RQ", "KMF", "Kam Air", "カーム航空"],
  ["FG", "AFG", "Ariana Afghan Airlines", "アリアナ・アフガン航空"],
  ["TZ", "SCO", "Scoot", "スクート"],
  ["TR", "SCO", "Scoot", "スクート"],
  ["QZ", "AWQ", "Indonesia AirAsia", "インドネシア・エアアジア"],
  ["TN", "THT", "Air Tahiti Nui", "エア タヒチ ヌイ"],
  ["I5", "IAD", "AIX Connect", "エアアジア・インディア"],
  ["3U", "CSC", "Sichuan Airlines", "四川航空"],
  ["PX", "ANG", "Air Niugini", "ニューギニア航空"],
  ["A5", "HOP", "Air France Hop", "オップ!"],
  ["OA", "OAL", "Olympic Air", null],
  ["WB", "RWD", "RwandAir", "ルワンダ航空"],
  ["FX", "FDX", "FedEx Express", "フェデックス・エクスプレス"],
  ["X3", "TUI", "TUI fly Deutschland", "TUIフライ"],
  ["W5", "IRM", "Mahan Air", "マーハーン航空"],
  ["6H", "ISR", "Israir Airlines", "イズレール航空"],
  ["CU", "CUB", "Cubana de Aviación", "クバーナ航空"],
  ["2R", null, "Via Rail", "VIA鉄道"],
  ["R3", "SYL", "Yakutia Airlines", "ヤクーツク航空"],
  ["V7", "VOE", "Volotea", "ボロテア"],
  ["VT", "VTA", "Air Tahiti", "エアタヒチ"],
  ["2L", "OAW", "Helvetic Airways", "ヘルヴェティック・エアウェイズ"],
  ["OR", "TFL", "TUI fly Netherlands", "アークフライ"],
  ["7J", "TJK", "Tajik Air", "タジキスタン航空"],
  ["CC", "ABD", "Air Atlanta Icelandic", "エア・アトランタ・アイスランディック"],
  ["RB", "SYR", "Syrian Air", "シリア・アラブ航空"],
  ["IY", "IYE", "Yemenia", "イエメニア"],
  ["V3", "KRP", "Carpatair", "カーペットエア"],
  ["SD", "SUD", "Sudan Airways", "スーダン航空"],
  ["BY", "TOM", "TUI Airways", "トムソン航空"],
  ["S4", "RZO", "Azores Airlines", "SATAインターナショナル"],
  ["G3", "GLO", "Gol Transportes Aéreos", "ゴル航空"],
  ["LM", "LOG", "Loganair", "ローガンエアー"],
  ["DT", "DTA", "TAAG Angola Airlines", "TAAGアンゴラ航空"],
  ["CL", "CLH", "Lufthansa CityLine", "ルフトハンザ・シティーライン"],
  ["SJ", "SJY", "Sriwijaya Air", "スリウィジャヤ航空"],
  ["2J", "VBW", "Air Burkina", "エール・ブルキナ"],
  ["XK", "CCM", "Air Corsica", "CCM航空"],
  ["BJ", "LBT", "Nouvelair", "ヌーベルエア"],
  ["E4", "ENT", "Enter Air", "エンター・エア"],
  ["K6", "KHV", "Air Cambodia", "エア・カンボジア"],
  ["NX", "AMU", "Air Macau", "マカオ航空"],
  ["SB", "ACI", "Aircalin", "エアカラン"],
  ["VF", "THY", "AJet", "アナドルジェット航空"],
  ["NY", "FXI", "Air Iceland", "エア・アイスランド"],
  ["WZ", "RWZ", "Red Wings Airlines", "レッドウィングス航空"],
  ["UO", "HKE", "HK Express", "香港エクスプレス航空"],
  ["SS", "CRL", "Corsair International", "コルセールフライ"],
  ["VI", "VDA", "Volga-Dnepr Airlines", "ヴォルガ・ドニエプル航空"],
  ["TB", "JAF", "TUI fly Belgium", "ジェットエアフライ"],
  ["5N", "AUL", "Nordavia", "ノルダヴィア"],
  ["VR", "TCV", "Cabo Verde Airlines", "TACVカーボベルデ航空"],
  ["OM", "MGL", "MIAT Mongolian Airlines", "MIATモンゴル航空"],
  ["WX", "BCY", "CityJet", "シティジェット"],
  ["BP", "BOT", "Air Botswana", "エア・ボツワナ"],
  ["BX", "ABL", "Air Busan", "エアプサン"],
  ["D3", "DAO", "Daallo Airlines", "ダーロ航空"],
  ["Y4", "VOI", "Volaris", "ボラリス"],
  ["HD", "ADO", "Air Do", "AIRDO"],
  ["5X", "UPS", "UPS Airlines", "UPS航空"],
  ["8L", "LKE", "Lucky Air", "雲南祥鵬航空"],
  ["TM", "LAM", "LAM Mozambique Airlines", "LAMモザンビーク航空"],
  ["GS", "GCR", "Tianjin Airlines", "天津航空"],
  ["HO", "DKH", "吉祥航空", "吉祥航空"],
  ["XY", "KNE", "フライナス", "フライナス"],
  ["UK", "VTI", "Vistara", "ビスタラ"],
  ["DP", "PBD", "Pobeda", "ポベーダ航空"],
  ["ZB", "ABN", "Air Albania", "エア・アルバニア"],
  ["OX", "OEA", "Orient Thai Airlines", "オリエント・タイ航空"],
  ["M0", "MNG", "Aero Mongolia", "アエロ・モンゴリア"],
  ["XC", "CAI", "Corendon Airlines", "コレンドン航空"],
  ["NF", "AVN", "Air Vanuatu", "バヌアツ航空"],
  ["D7", "XAX", "AirAsia X", "エアアジア X"],
  ["LD", "AHK", "Air Hong Kong", "エア・ホンコン"],
  ["H2", "SKU", "Sky Airline", "スカイ航空"],
  ["WT", "SWT", "Swiftair", "スウィフトエア"],
  ["NT", "IBB", "Binter Canarias", "ビンテル・カナリアス"],
  ["BC", "SKY", "Skymark Airlines", "スカイマーク"],
  ["9C", "CQH", "Spring Airlines", "春秋航空"],
  ["AE", "MDA", "Mandarin Airlines", "マンダリン航空"],
  ["SC", "CDG", "Shandong Airlines", "山東航空"],
  ["7C", "JJA", "Jeju Air", "済州航空"],
  ["JD", "CBJ", "Beijing Capital Airlines", "北京首都航空"],
  ["OD", "MXD", "Batik Air Malaysia", "バティック・エア・マレーシア"],
  ["EE", "EST", "Nordica", "ノルディカ航空"],
  ["LN", "LAA", "Libyan Airlines", "リビア航空"],
  ["BW", "BWA", "カリビアン航空", "カリビアン航空"],
  ["JE", "MNO", "Mango", "マンゴー航空"],
  ["BK", "OKA", "Okay Airways", "奥凱航空"],
  ["6B", "BLX", "TUIfly Nordic", "TUIフライ・ノルディック"],
  ["ID", "BTK", "Batik Air", "バティック・エア"],
  ["SY", "SCX", "Sun Country Airlines", "サン・カントリー航空"],
  ["GZ", "RAR", "Air Rarotonga", "ラロトンガ航空"],
  ["V0", "VCV", "Conviasa", "コンビアサ航空"],
  ["FH", "FHY", "Freebird Airlines", "フリーバード航空"],
  ["CY", "CYP", "Cyprus Airways", "チャーリー・エアラインズ"],
  ["D8", "NSW", "Norwegian Air Sweden", "ノルウェー・エア・スウェーデン"],
  ["CJ", "CFE", "BA CityFlyer", "BAシティフライヤー"],
  ["WF", "WIF", "Widerøe", "ヴィデロー航空"],
  ["DS", "EZS", "EasyJet Switzerland", "イージージェット・スイス"],
  ["TV", "TBA", "Tibet Airlines", "チベット航空"],
  ["PY", "SLM", "Surinam Airways", "スリナム・エアウェイズ"],
  ["6R", "DRU", "ALROSA Air Company", "アルローサ航空"],
  ["5Y", "GTI", "Atlas Air", "アトラス航空"],
  ["FD", "AIQ", "Thai AirAsia", "タイ・エアアジア"],
  ["TY", "TPC", "Air Calédonie", "エール・カレドニー"],
  ["TX", "FWI", "Air Caraïbes", "エア・カライベス"],
  ["DV", "VSV", "SCAT Airlines", "SCAT航空"],
  ["NI", "PGA", "Portugália", "ポルトガリア航空"],
  ["FY", "FFM", "Firefly", "ファイアフライ航空"],
  ["RV", "CPN", "カスピアン航空", "カスピアン航空"],
  ["2K", "GLG", "Avianca Ecuador", "アビアンカ・エクアドル航空"],
  ["EP", "IRC", "イラン・アーセマーン航空", "イラン・アーセマーン航空"],
  ["B8", "ERT", "Eritrean Airlines", "エリトリア航空"],
  ["WE", "THD", "Thai Smile", "タイ・スマイル"],
  ["6J", "JUB", "Jubba Airways", "ジュッバ航空"],
  ["ZP", "AZQ", "Silk Way Airline", "シルクウェイ航空"],
  ["4G", "GZP", "Gazprom Avia", "ガスプロムアヴィア"],
  ["QK", "JZA", "Jazz Aviation", "ジャズ航空"],
  ["DH", "NAN", "Norwegian Air Norway", "ノルウェー・エア・ノルウェー"],
  ["NO", "NOS", "Neos", "ネオス"],
  ["KX", "CAY", "Cayman Airways", "ケイマン航空"],
  ["Y7", "TYA", "Taimyr Air Company", "ノルドスター航空"],
  ["3V", "TAY", "ASL Airlines Belgium", "TNT航空"],
  ["OO", "SKW", "SkyWest Airlines", "スカイウェスト航空"],
  ["3S", "BOX", "AeroLogic", "アエロロジック"],
  ["UG", "TUX", "Tunisair Express", "チュニスエア・エクスプレス"],
  ["9J", "DAN", "Dana Air", "ダナ航空"],
  ["LP", "LPE", "LATAM Airlines Peru", "ラタム・ペルー"],
  ["UP", "BHS", "バハマスエア", "バハマスエア"],
  ["QG", "CTV", "Citilink", "シティリンク"],
  ["2U", "ERO", "Sun d'Or International Airlines", "サンドア国際航空"],
  ["R5", "JAV", "Jordan Aviation", "ヨルダン・アビエーション"],
  ["EU", "UEA", "Chengdu Airlines", "成都航空"],
  ["TO", "TVF", "Transavia France", "トランサヴィア・フランス"],
  ["DK", "VKG", "Sunclass Airlines", "サンクラス航空"],
  ["H6", "BUC", "European Air Charter", "ブルガリア・エア・チャーター"],
  ["YC", "LLM", "Yamal Airlines", "ヤマル航空"],
  ["5O", "FPO", "ASL Airlines France", "ヨーロッパ・エアポスト"],
  ["9I", "LLR", "Alliance Air", "エア・インディア・リージョナル"],
  ["5C", "ICL", "Challenge Airlines IL", "CALカーゴ・エアラインズ"],
  ["N4", "NWS", "Nordwind Airlines", "ノードウィンド航空"],
  ["4C", "ARE", "LATAM Airlines Colombia", "ラン・コロンビア"],
  ["I2", "IBS", "Iberia Express", "イベリア・エクスプレス"],
  ["N7", "FCM", "Nordic Regional Airlines", "フライビー・ノルディック航空"],
  ["IL", "TGN", "Trigana Air Service", "トリガナ航空"],
  ["EB", "PLM", "Wamos Air", "プルマントゥール・エア"],
  ["3K", "JSA", "Jetstar Asia Airways", "ジェットスター・アジア航空"],
  ["TW", "TWB", "T'way Airlines", "ティーウェイ航空"],
  ["KN", "CUA", "China United Airlines", "中国聯合航空"],
  ["RU", "ABW", "AirBridgeCargo Airlines", "エアブリッジ・カーゴ"],
  ["GR", "AUR", "Aurigny Air Services", "オーリニー・エア・サービス"],
  ["3O", "MAC", "Air Arabia Maroc", "エア・アラビア・モロッコ"],
  ["VB", "VIV", "Viva", "ビバアエロバス"],
  ["6Y", "ART", "スマートリンクス航空", "スマートリンクス航空"],
  ["4D", "ASD", "Air Sinai", "エアシナイ"],
  ["NL", "SAI", "Shaheen Air", "シャーヒーン航空"],
  ["SZ", "SMR", "Somon Air", "サモンエア"],
  ["B3", "BTN", "Bhutan Airlines", "タシ航空"],
  ["2G", "AGU", "Angara Airlines", "アンガラ航空"],
  ["MM", "APJ", "Peach", "Peach Aviation"],
  ["0V", "VFC", "Vietnam Air Services Company", "ベトナムエアサービス"],
  ["BS", "UBG", "US-Bangla Airlines", "USバングラエアラインズ"],
  ["U8", "CYF", "Tus Airways", "タス・エアウェイズ"],
  ["DN", "NAA", "ノルウェージャン・エア・アルゼンティナ", "ノルウェージャン・エア・アルゼンティナ"],
  ["ZL", "RXA", "Rex Airlines", "リージョナルエクスプレス航空"],
  ["MY", "MWG", "MASwings", null],
  ["KG", "GTV", "Aerogaviota", "アエロガビオータ"],
  ["SF", "DTH", "Domestic Airlines", "タッシリ航空"],
  ["DX", "DTR", "DAT", "ダニッシュ・エア・トランスポート"],
  ["HF", "VRE", "Air Côte d'Ivoire", "エール・コートジボワール"],
  ["XL", "LNE", "LATAM Airlines Ecuador", "ラン・エクアドル"],
  ["YU", "MMZ", "EuroAtlantic Airways", "ユーロアトランティック航空"],
  ["LL", "LVL", "Level", "レベル"],
  ["7W", "WRC", "Windrose Airlines", "ウインドローズ航空"],
  ["Z2", "APG", "Philippines AirAsia", "エアアジア・フィリピン"],
  ["OB", "BOV", "Boliviana de Aviación", "ボリビアーナ航空"],
  ["3H", "AIE", "Air Inuit", "エア・イヌイット"],
  ["IK", "AKL", "Air Kiribati", "キリバス航空"],
  ["Q2", "DQA", "Maldivian", "モルディビアン"],
  ["5K", "HFY", "Hi Fly", "ハイフライ航空"],
  ["ZF", "KTK", "Azur Air", "アズール・エア"],
  ["MQ", "ENY", "Envoy Air", "エンヴォイ・エア"],
  ["YJ", "AMV", "AMC Airlines", "AMC航空"],
  ["QX", "QXE", "Horizon Air", "ホライゾン航空"],
  ["SP", "SAT", "SATA Air Açores", "SATA エア・アゾレス"],
  ["A4", "MUT", "Azimuth", "アジムート航空"],
  ["PZ", "LAP", "LATAM Airlines Paraguay", "TAMメルコスール"],
  ["UQ", "CUH", "Urumqi Air", "ウルムチ・エア"],
  ["OV", "OMS", "SalamAir", "サラムエア"],
  ["N0", "NBT", "Norse Atlantic Airways", "ノースアトランティック航空"],
  ["JO", "JTD", "Jet Time", "ジェット・タイム"],
  ["LJ", "JNA", "Jin Air", "ジンエアー"],
  ["PN", "CHB", "West Air", "中国西部航空"],
  ["ZT", "AWC", "Titan Airways", "タイタン・エアウェイズ"],
  ["6L", "NTH", "Hokkaido Air System", "北海道エアシステム"],
  ["NU", "JTA", "Japan Transocean Air", "日本トランスオーシャン航空"],
  ["4Z", "LNK", "Airlink", "エアリンク"],
  ["XM", "JLJ", "J-Air", "ジェイエア"],
  ["OL", "PAO", "Samoa Airways", "ポリネシアン航空"],
  ["MB", "MNB", "MNG Airlines", "MNG航空"],
  ["8M", "MMA", "Myanmar Airways International", "ミャンマー国際航空"],
  ["8H", "BGH", "BH Air", "BHエア"],
  ["1B", "BGH", "BH Air", "BHエア"],
  ["T3", "EZE", "Eastern Airways", "イースタン航空 (イギリス)"],
  ["JH", "FDA", "Fuji Dream Airlines", "フジドリームエアラインズ"],
  ["GB", "ABX", "ABX Air", "ABXエア"],
  ["CN", "GDC", "Grand China Air", "大新華航空"],
  ["NQ", "AJX", "Air Japan", "エアージャパン"],
  ["K4", "CKS", "Kalitta Air", "カリッタ・エア"],
  ["HZ", "SHU", "Aurora", "オーロラ"],
  ["RS", "ASV", "Air Seoul", "エアソウル"],
  ["JX", "SJX", "Starlux Airlines", "スターラックス航空"],
  ["4Y", "OCN", "Discover Airlines", "ユーロウイングス・ディスカバー"],
  ["ZE", "ESR", "Eastar Jet", "イースター航空"],
  ["NS", "HBH", "Hebei Airlines", "河北航空"],
  ["OQ", "CQN", "Chongqing Airlines", "重慶航空"],
  ["CK", "CKK", "China Cargo Airlines", "中国貨運航空"],
  ["7R", "RLU", "RusLine", "ラスライン"],
  ["ST", "RTL", "Air Thanlwin", "ヤンゴン航空"],
  ["WI", "WHT", "White Airways", "ホワイト・エアウェイズ"],
  ["Y8", "YZR", "Suparna Airlines", "揚子江快運航空"],
  ["N8", "NCR", "National Airlines", "ナショナル航空 (N8)"],
  ["B7", "UIA", "Uni Air", "ユニー航空"],
  ["IO", "IAE", "IrAero", "イル・アエロ"],
  ["PD", "POE", "Porter Airlines", "ポーター航空"],
  ["IE", "SOL", "Solomon Airlines", "ソロモン航空"],
  ["EF", "EZA", "Eznis Airways", "エズニス航空"],
  ["4N", "ANT", "Air North", "エア・ノース"],
  ["TH", "RMY", "Raya Airways", "トランスマイル・エア・サービス"],
  ["6Q", "SAW", "Cham Wings Airlines", "シャーム・ウィングス航空"],
  ["GJ", "CDC", "Loong Air", "長竜航空"],
  ["SL", "TLM", "Thai Lion Air", "タイ・ライオン・エア"],
  ["EL", "ELB", "Ellinair", "エリン航空"],
  ["BF", "FBU", "French Bee", "フレンチブルー"],
  ["F3", "FAD", "flyadeal", "フライアディール"],
  ["2B", "AWT", "Albawings", "アルバウィングス"],
  ["P2", "XAK", "Airkenya Express", null],
  ["JW", "VNL", "Vanilla Air", "バニラ・エア"],
  ["QU", "UTN", "Skyline Express Airlines", "UTエアー・ウクライナ"],
  ["9H", "CGN", "Air Changan", "長安航空"],
  ["KP", "SKK", "Asky Airlines", "ASKY航空"],
  ["XU", "AXK", "African Express Airways", "アフリカン・エクスプレス・エアウェイズ"],
  ["5D", "SLI", "Aeroméxico Connect", "アエロメヒコ・コネクト"],
  ["DZ", "EPA", "Donghai Airlines", "深圳東海航空"],
  ["EZ", "SUS", "Sun Air of Scandinavia", "サン・エア"],
  ["PT", "SWN", "West Atlantic Sweden", "ウエスト・エア・スウェーデン"],
  ["E5", "RBG", "Air Arabia Egypt", "エア・アラビア・エジプト"],
  ["Y9", "KIS", "キーシュ航空", "キーシュ航空"],
  ["5H", "FFV", "Fly540", "フライ540"],
  ["GQ", "SEH", "スカイ・エクスプレス", "スカイ・エクスプレス"],
  ["CG", "TOK", "PNG Air", "PNG航空"],
  ["IW", "WON", "Wings Air", "ウィングス・エア"],
  ["7G", "SFJ", "StarFlyer", "スターフライヤー"],
  ["BZ", "BDA", "Blue Dart Aviation", "ブルーダート・アビエーション"],
  ["PW", "PRF", "Precision Air", "プレシジョンエア"],
  ["YV", "ASH", "Mesa Airlines", "メサ航空"],
  ["M4", "MSA", "Poste Air Cargo", "ミストラル・エア"],
  ["UZ", "BRQ", "Buraq Air", "ブラク航空"],
  ["JR", "JOY", "Joy Air", "幸福航空"],
  ["KZ", "NCA", "Nippon Cargo Airlines", "日本貨物航空"],
  ["US", "JIA", "PSA Airlines", "PSA航空"],
  ["VH", "VVC", "Viva Air Colombia", "ビバコロンビア"],
  ["2M", "MYD", "Maya Island Air", "マヤ・アイランド・エアー"],
  ["RX", "RGE", "Regent Airways", "リージェント・エアウェイズ"],
  ["L6", "MAI", "Mauritania Airlines", "モーリタニア航空インターナショナル"],
  ["AQ", "JYH", "9 Air", "9エア"],
  ["7L", "AZG", "Silk Way West Airlines", "シルクウェイウエスト航空"],
  ["B0", "DJT", "La Compagnie", "ラ・カンパニー"],
  ["5F", "FIA", "FlyOne", "フライワン"],
  ["PQ", "SQP", "SkyUp", "スカイアップ"],
  ["V8", "VAS", "ATRAN", null],
  ["AJ", "NIG", "Aero Contractors", "エアロ・コントラクターズ"],
  ["G5", "HXA", "China Express Airlines", "華夏航空"],
  ["GK", "JJP", "Jetstar Japan", "ジェットスター・ジャパン"],
  ["P4", "APK", "Air Peace", "エアピース"],
  ["LU", "LXP", "ラン・エクスプレス", "ラン・エクスプレス"],
  ["7P", "PST", "エア・パナマ", "エア・パナマ"],
  ["9V", "ROI", "Avior Airlines", "アビオール・エアラインズ"],
  ["PO", "PAC", "Polar Air Cargo", "ポーラーエアカーゴ"],
  ["J4", "BFL", "Buffalo Airways", "バッファロー・エアウェイズ"],
  ["P9", "PVN", "ペルビアン航空", "ペルビアン航空"],
  ["HH", "TBN", "ターバーン航空", "ターバーン航空"],
  ["WM", "WIA", "Winair", "ウィンエアー"],
  ["AG", "ABR", "ASL Airlines Ireland", "コントラクター航空"],
  ["8F", "STP", "STP Airways", "STP航空"],
  ["FW", "IBX", "Ibex Airlines", "アイベックスエアラインズ"],
  ["SI", "BCI", "Blue Islands", "ブルー・アイランズ"],
  ["FS", null, "FlyArystan", "フライアリスタン"],
  ["C2", "CEL", "CEIBA Intercontinental", "CEIBAインターコンチネンタル"],
  ["XH", "KHH", "Alexandria Airlines", "アレクサンドリア航空"],
  ["T0", "TPU", "Avianca Peru", "TACAペルー航空"],
  ["2I", "SRU", "Star Perú", "スターペルー航空"],
  ["M8", "TMW", "Trans Maldivian Airways", "トランスモルディブ航空"],
  ["IT", "TTW", "Tigerair Taiwan", "タイガーエア台湾"],
  ["W8", "CJT", "Cargojet", "カーゴジェット"],
  ["CF", "CYZ", "China Postal Airlines", "中国貨運郵政航空"],
  ["NP", "NIA", "Nile Air", "ナイル航空"],
  ["DG", "SRQ", "Cebgo", "サウスイースト・アジアンエアラインズ"],
  ["TA", null, "Avianca El Salvador", "アビアンカ・エルサルバドル"],
  ["BN", "BAB", "Bahrain Air", "バーレーン航空"],
  ["P5", "RPB", "Copa Airlines Colombia", "コパ航空コロンビア"],
  ["YN", "CRQ", "Air Creebec", "クリーベック航空"],
  ["TI", "TWI", "Tailwind Airlines", "テイルウィンド・エアラインズ"],
  ["6D", "PAS", "Pelita Air Service", "ペリタ・エアサービス"],
  ["TL", "ANO", "Airnorth", "エアノース"],
  ["D6", "ILN", "Interair South Africa", "インターエア・サウスアフリカ"],
  ["JC", "JAC", "Japan Air Commuter", "日本エアコミューター"],
  ["QC", "CRC", "Camair-Co", "カメルーン航空"],
  ["B9", "IRB", "イランエアツアーズ", "イランエアツアーズ"],
  ["CD", "CND", "Corendon Dutch Airlines", "コレンドン・ダッチ航空"],
  ["6T", "AMY", "Air Mandalay", "マンダレー航空"],
  ["CW", "MRS", "Air Marshall Islands", "マーシャル諸島航空"],
  ["7O", "TVL", "Smartwings Hungary", "トラベルサービス・ハンガリー"],
  ["OE", "CCE", "Cairo Aviation", "カイロ航空"],
  ["NE", "NMA", "Nesma Airlines", "ネスマ航空"],
  ["Q8", "TSG", "トランスエアコンゴ", "トランスエアコンゴ"],
  ["KY", "KNA", "Kunming Airlines", "昆明航空"],
  ["RI", "MDL", "Mandala Airlines", "マンダラ航空"],
  ["VZ", "TVJ", "Thai Vietjet Air", "タイ・ベトジェットエア"],
  ["FN", "RXP", "Royal Air Maroc Express", "ロイヤル・エア・モロッコ・エクスプレス"],
  ["VQ", "NVQ", "NovoAir", "ノヴォエア"],
  ["YK", "AVJ", "Avia Traffic Company", "アヴィア・トラフィック・カンパニー"],
  ["P8", "SRN", "SprintAir", "スプリントエア"],
  ["QW", "QDA", "Qingdao Airlines", "青島航空"],
  ["DR", "RLH", "Ruili Airlines", "瑞麗航空"],
  ["FU", "FZA", "Fuzhou Airlines", "福州航空"],
  ["QP", "AKJ", "Akasa Air", "アカサ・エア"],
  ["KM", "KMM", "KM Malta Airlines", "KMマルタ航空"],
  ["R7", "OCA", "Aserca Airlines", null],
  ["E9", "EVE", "Evelop Airlines", null],
  ["FO", "FXX", "Felix Airways", "フェリック航空"],
  ["GH", "GLP", "Globus", "グローバス航空"],
  ["ZA", "SWM", "Sky Angkor Airlines", "スカイ・アンコール航空"],
  ["KW", "WAN", "Wataniya Airways", "ワターニーヤ航空"],
  ["4I", "IZM", "IZair", "イズ・エアー"],
  ["QT", "TPA", "Avianca Cargo", "タンパ・カーゴ"],
  ["H7", "EGU", "Eagle Air", "イーグル・エア"],
  ["JV", "BLS", "Bearskin Airlines", "ベアスキン航空"],
  ["J8", "BVT", "Berjaya Air", "ベルジャヤ航空"],
  ["UJ", "LMU", "AlMasria Universal Airlines", "アルマシーラ・ユニバーサル航空"],
  ["B1", "BUR", "Air Bucharest", "エア・ブカレスト"],
  ["BU", "DBP", "コンパニ－・アフリケーヌ・ダビアシオン", "コンパニ－・アフリケーヌ・ダビアシオン"],
  ["2P", "GAP", "Airphil Express", "エアフィル・エクスプレス"],
  ["HP", "APF", "Amapola Flyg", "アマポーラフリーグ"],
  ["4H", "UBD", "United Airways", "ユナイテッド・エアウェイズ"],
  ["T7", "TJT", "Twin Jet", "ツインジェット"],
  ["BO", "BBD", "Bluebird Nordic", "ブルーバード・カーゴ"],
  ["MR", "MML", "Hunnu Air", "モンゴリアン・エアラインズ"],
  ["7I", "TLR", "Air Libya", "エア・リビア"],
  ["4B", "TUP", "Aviastar-TU", "アヴィアスタル-TU"],
  ["9T", "RUN", "Air ACT", "ACT航空"],
  ["6N", "MHK", "Al-Naser Airlines", "アル・ナセル航空"],
  ["KS", "PEN", "PenAir", "ペンエアー"],
  ["FA", "SFR", "Safair", "サフエアー"],
  ["ZK", "GLA", "Great Lakes Airlines", "グレイトレイクス航空"],
  ["EH", "AKX", "ANA Wings", "ANAウイングス"],
  ["EC", "EJU", "easyJet Europe", "イージージェット・ヨーロッパ"],
  ["JF", "JAA", "Jet Asia Airways", "ジェットアジア・エアウェイズ"],
  ["I3", "TBZ", "アタ航空", "アタ航空"],
  ["XP", "VXP", "Avelo Airlines", "エクストレイ航空"],
  ["XJ", "TAX", "Thai AirAsia X", "タイ・エアアジア X"],
  ["JM", "KQA", "Jambojet", "ジャンボジェット"],
  ["3W", "MWI", "Malawi Airlines", "マラウイアン航空"],
  ["DM", "DWI", "フライカナ", "フライカナ"],
  ["ZQ", "MNE", "Air Montenegro", "エア・モンテネグロ"],
  ["XT", "IDX", "Indonesia AirAsia X", "インドネシア・エアアジア X"],
  ["8Z", "CGA", "コンゴ・エアウェイズ", "コンゴ・エアウェイズ"],
  ["ZG", "TZP", "ZIPAIR Tokyo", null],
  ["E6", "EWL", "Eurowings Europe", "ユーロウイングス・ヨーロッパ"],
  ["EV", "ASQ", "ExpressJet", "エクスプレスジェット航空"],
  ["6G", "RLX", "Go2Sky", null],
  ["OY", "ANS", "アンデス･ライネア･アエレアス", "アンデス･ライネア･アエレアス"],
  ["JA", "JAT", "JetSmart", "ジェットスマート"],
  ["QL", "LER", "LASER Airlines", "LASER航空"],
  ["MW", "MAY", "Malta Air", "マルタエア"],
  ["9M", "GLR", "Central Mountain Air", "セントラル・マウンテン航空"],
  ["9E", "FLG", "Endeavor Air", "エンデバー・エア"],
  ["F8", "FLE", "Flair Airlines", "フレア航空"],
  ["UF", "PER", "Petroleum Air Services", "ペトロレウム・エア・サービス"],
  ["YF", null, "Department of National Defence", "カナダの国防省"],
  ["H5", "RSY", "I-Fly", "I-フライ"],
  ["9K", "KAP", "Cape Air", "ケープエアー"],
  ["AP", "LAV", "AlbaStar", "アルバスター"],
  ["NC", "JTE", "National Jet Express", "コバム航空オーストラリア"],
  ["PJ", "SPM", "Air Saint-Pierre", "エール・サン＝ピエール"],
  ["PI", "RKA", "Polar Airlines", "ポーラーエアラインズ"],
  ["ZR", "AZS", "Aviacon Zitotrans", "アヴィアコン・ツィタトランス"],
  ["P6", "PVG", "Privilege Style", "プリビリッジ・スタイル"],
  ["VE", "EFY", "Clic Air", "イージーフライ"],
  ["UC", "LCO", "LATAM Cargo Chile", "ラン・カーゴ"],
  ["Z8", "AZN", "Línea Aérea Amaszonas", "アマソナス航空"],
  ["IS", "PNX", "AIS Airlines", "AIS エアラインズ"],
  ["DC", "BRX", "Braathens Regional", "ゴールデン・エア"],
  ["6O", "OBS", "Orbest", "オーベスト航空"],
  ["WP", "MKU", "Island Air (Hawaii)", "アイランドエアー"],
  ["QQ", "UTY", "Alliance Airlines", "アライアンス航空"],
  ["GX", "CBG", "GX Airlines", "北部湾航空"],
  ["8E", "BRG", "Bering Air", "ベーリング・エア"],
  ["MO", "CAV", "Calm Air", null],
  ["AW", "AFW", "アフリカ・ワールド航空", "アフリカ・ワールド航空"],
  ["O3", "CSS", "SF Airlines", "順豊航空"],
  ["KI", "KRS", "KrasAvia", "クラスアビア"],
  ["R6", "DNU", "DOT LT", null],
  ["IJ", "SJO", "Spring Airlines Japan", "スプリング・ジャパン"],
  ["IN", "NIH", "NAM Air", "ナム・エア"],
  ["CS", "GSW", "チェアー航空", "チェアー航空"],
  ["RM", "NGT", "Air Dilijans", "アルメニア・エアカンパニー"],
  ["YP", "APZ", "Air Premia", "エアプレミア"],
  ["XZ", "AEZ", "Aeroitalia", "アエロ・イタリア"],
  ["RP", "BPS", "Budapest Aircraft Service", null],
  ["XA", null, "ARINC", null],
  ["GU", "GUG", "アヴィアテカ航空", "アヴィアテカ航空"],
  ["5U", "LDE", "Líneas Aéreas del Estado (LADE)", "LADE"],
  ["ES", "DHX", "DHL International Aviation ME", null],
  ["MZ", "AHX", "Amakusa Airlines", "天草エアライン"],
  ["LR", "LRC", "Avianca Costa Rica", "LACSA航空"],
  ["5T", "MPE", "Canadian North", "カナディアン・ノース"],
  ["LW", "LDA", "Lauda Europe Ltd", null],
  ["KH", "AAH", "Aloha Air Cargo", "アロハ・エアカーゴ"],
  ["OC", "ORC", "Oriental Air Bridge", "オリエンタルエアブリッジ"],
  ["YX", "RPA", "Republic Airways", "リパブリック航空"],
  ["3M", "SIL", "Silver Airways", "シルバー・エアウェイズ"],
  ["RY", "RYW", "Royal Wings", "ロイヤル・ウイングス航空"],
  ["K7", "KBZ", "Mingalar Aviation Services", "エア・カンボーザ"],
  ["M3", "LTG", "ABSAカーゴ", "ABSAカーゴ"],
  ["M7", "MAA", "MasAir Cargo Mexico", "マスエア"],
  ["1I", "EJA", "NetJets", "ネット・ジェッツ"],
  ["I8", "IZA", "Izhavia", "イジャヴィア"],
  ["QB", "QSM", "ゲシュム航空", "ゲシュム航空"],
  ["3G", "CXM", "World Cargo Airlines", "ギャディング・サリ・アヴィエーション・サービス"],
  ["LK", "LLL", "Lao Air", "ラオ・スカイウェイ"],
  ["3Z", "TVP", "Smartwings Poland", "スマートウィングス・ポーランド"],
  ["E3", "VGO", "New Gen Airways", "ニュージェン・エアウェイズ"],
  ["IQ", "QAZ", "Qazaq Air", "カザク・エア"],
  ["H9", "HIM", "Himalaya Airlines", "ヒマラヤ航空"],
  ["LQ", "MKR", "Lanmei Airlines", "ランメイ・エアラインズ"],
  ["HC", "SZN", "Air Senegal", "エア・セネガル"],
  ["6W", "FBS", "FlyBosnia", "フライボスニア"],
  ["KR", "KME", "Cambodia Airways", "カンボジア・エアウェイズ"],
  ["MX", "MXY", "Breeze Airways", "ブリーズ・エアウェイズ"],
  ["C3", "TDR", "Trade Air", null],
  ["5B", "NCH", "Chanchangi Airlines", "チャンチャンギ航空"],
  ["GM", "TMG", "Asia Cargo Airlines", "トライエムジー・イントラ・アジア航空"],
  ["DJ", "DJU", "Air Djibouti", "エール・ジブチ"],
  ["5M", "HFM", "Hi Fly Malta", "ハイフライ・マルタ"],
  ["4W", "AJK", "Allied Air", "アライド・エア"],
  ["YO", "MCM", "Heli Air Monaco", "ヘリ・エア・モナコ"],
  ["OF", "OLA", "Overland Airways", "オーバーランド航空"],
  ["SH", null, "Sharp Airlines", "シャープ・エアラインズ"],
  ["7Y", "MYP", "Mann Yatanarpon Airlines", "マン・ヤダナルポン航空"],
  ["L5", "LTR", "Lufttransport", "ルフト・トランスポート"],
  ["HS", "HSV", "Direktflyg", "ディレクトフリーグ"],
  ["GO", "KZU", "ULS Airlines Cargo", "ULSエアラインズ・カーゴ"],
  ["M9", "MSI", "Motor Sich Airlines", "モトール・シーチ航空"],
  ["3N", "URG", "Air Urga", "ウラガ航空"],
  ["9L", "TOW", "AirTanker Services Limited", null],
  ["JY", "IWY", "InterCaribbean Airways", "インターカリビアン航空"],
  ["TD", "LUR", "Atlantis Armenian Airlines", "アトランティス・ヨーロピアン・エアラインズ"],
  ["MV", "VIT", "Aviastar", "アヴィアスター"],
  ["IF", "FBA", "Fly Baghdad", "フライバグダード"],
  ["KJ", "AIH", "Air Incheon", "エア・インチョン"],
  ["PM", "CNF", "Canaryfly", "カナリーフライ"],
  ["YE", "ANR", "Yanair", "ヤン航空"],
  ["TF", null, "BRA Braathens Regional Airlines", "ブラーテンズ・リージョナル・エアラインズ"],
  ["XR", "CXI", "Corendon Airlines Europe", "コレンドン航空ヨーロッパ"],
  ["W9", "WUK", "Wizz Air UK", "ウィズエアー UK"],
  ["UR", "UGD", "ウガンダ航空", "ウガンダ航空"],
  ["3F", "FIE", "フライワン・アルメニア", "フライワン・アルメニア"],
  ["2W", "WFL", "World2Fly", "ワールド2フライ"],
  ["2S", "STW", "Southwind Airlines", "サウスウィンド航空"],
  ["D4", "LID", "Alidaunia", null],
  ["3B", "JBR", "Central Connect Airlines", null],
  ["FE", "IHO", "748 Air Services", null],
  ["GW", "GJT", "GetJet Airlines", null],
  ["BQ", "SWU", "Sky Alps", null],
  ["Q6", "SKP", "SmartLynx Australia", "スカイトランス航空"],
  ["6C", "KRE", "Aerosucre", "アエロスクレ"],
  ["XW", "CXH", "China Xinhua Airlines", "中国新華航空"],
  ["V5", "DAP", "DAP航空", "DAP航空"],
  ["C5", "UCA", "CommuteAir", "コミュートエア"],
  ["WC", "ISV", "Avianca Honduras", "イスレナ航空"],
  ["K8", "KND", "Kan Air", "カン・エア"],
  ["8P", "PCO", "Pacific Coastal Airlines", "パシフィック・コースタル航空"],
  ["LC", "EQR", "エクアトリアル・コンゴ・エアラインズ", "エクアトリアル・コンゴ・エアラインズ"],
  ["8B", "BCC", "Business Air", "ビジネス・エア"],
  ["N5", "MDM", "Medavia", "メダヴィア"],
  ["X7", "AGB", "Air Service Gabon", null],
  ["YB", null, "Harbour Air", "ハーバー・エア"],
  ["4K", "KBA", "Kenn Borek Air", "ケーン・ボーレック航空"],
  ["PV", "SBU", "St Barth Commuter", "セント・バーツコミューター"],
  ["9R", "NSE", "SATENA", "SATENA航空"],
  ["AL", "TXC", "TransAVIAexport Airlines", "トランス・アビア・エクスポート航空"],
  ["CE", "CLG", "Chalair Aviation", "シャレール航空"],
  ["8V", "ACP", "Astral Aviation", "アストラル・アビエーション"],
  ["NV", "IRG", "イラニアン・ナフト航空", "イラニアン・ナフト航空"],
  ["7V", "FDR", "Federal Air", "フェデラル・エア"],
  ["G1", "IKA", "Gorkha Airlines", "ゴルカ航空"],
  ["G7", "GJS", "GoJet Airlines LLC", "ゴー・ジェット航空"],
  ["P0", "PFZ", "Proflight Zambia", "プロフライト・ザンビア"],
  ["C8", "ICV", "Cargolux Italia", "カーゴルックス・イタリア"],
  ["PB", "PVL", "PAL Airlines", "プロビンシャル・エアラインズ"],
  ["5Z", "BML", "Bismillah Airlines", "ビスミラー航空"],
  ["7Z", "EZR", "Z Air", null],
  ["RG", "RJD", "Rotana Jet", "ロタナ・ジェット"],
  ["0G", null, "Ghadames Air Transport", "ガダメス航空"],
  ["5V", "VTS", "Everts Air", null],
  ["3T", "TQQ", "Tarco Aviation", "タルコ航空"],
  ["WR", "WEN", "WestJet Encore", "ウエストジェット・エンコア"],
  ["ZV", "VAX", "V Air", "V air"],
  ["RE", "REA", "Aer Arann Islands", "エアーアラン・アイランズ"],
  ["2D", "EAL", "Eastern Airlines, LLC", "ダイナミック航空"],
  ["KD", "WGN", "Western Global Airlines", "ウエスタン・グローバル・エアラインズ"],
  ["8W", "PWF", "Private Wings", null],
  ["ER", "SEP", "Serene Air", "セレーンエア"],
  ["6A", "AMW", "Armenia Airways", "アルメニア・エアウェイズ"],
  ["UB", "UBA", "Myanmar National Airlines", "ミャンマー・ナショナル航空"],
  ["VL", "LHX", "Lufthansa City Airlines", "ルフトハンザ・シティ航空"],
  ["J3", "PLR", "Northwestern Air", null],
  ["8T", "TID", "Air Tindi", null],
  ["2N", "UMK", "Yuzhmashavia", null],
  ["3R", "DVR", "Divi Divi Air", null],
  ["ZM", "CNB", "CityLine Hungary", null],
  ["WV", "RVP", "Aero VIP", null],
  ["YI", "RSI", "Air Sunshine", null],
  ["OJ", "NYX", "Nyxair", null],
  ["L7", "LAE", "LATAM Cargo Colombia", "ランコ"],
  ["NM", "NZM", "Mount Cook Airline", "マウントクック航空"],
  ["ZW", "AWI", "Air Wisconsin", "エア・ウィスコンシン"],
  ["S6", "KSZ", "Sunrise Airways", null],
  ["D0", "DHK", "DHL Air UK", "DHLエアUK"],
  ["5R", "RUC", "RUTACA Airlines", "ルタカ航空"],
  ["QY", "BCS", "European Air Transport Leipzig", "ヨーロピアン・エア・トランスポート・ライプツィヒ"],
  ["PE", "PEV", "People's", "ピーポーズ・ヴィエナライン"],
  ["9A", "EZX", "Eaglexpress", "イーグレクスプレス"],
  ["D2", "SSF", "Severstal Air Company", "セヴェルスタリ航空"],
  ["RZ", "LRS", "SANSA", "サンサ航空"],
  ["TE", "IGA", "Skytaxi", "スカイタクシー"],
  ["HQ", "TCW", "Thomas Cook Airlines Belgium", "トーマス・クック航空 (ベルギー)"],
  ["8D", null, "Servant Air", null],
  ["2F", "IRP", "Payam Air", "パヤム・エア"],
  ["KO", "KMA", "Komiaviatrans", "コミアヴィアトランス"],
  ["UI", "AUK", "Auric Air", "オーリックエア"],
  ["8K", "KMI", "K-Mile Air", "Kマイル・アジア"],
  ["6S", "SGQ", "Saudigulf", "サウディガルフ・エアラインズ"],
  ["L1", "TTL", "トータル・リンハス・アエレアス", "トータル・リンハス・アエレアス"],
  ["8J", "ECO", "EcoJet", "エコジェット (航空会社)"],
  ["6I", "MMD", "Air Alsie", null],
  ["ZD", "EWR", "Ewa Air", "エワ航空"],
  ["PU", "PUE", "Plus Ultra Líneas Aéreas", "プラス・ウルトラ・エアラインズ"],
  ["P3", "CLU", "CargoLogicAir", "カーゴロジックエア"],
  ["GT", "CGH", "Air Guilin", "桂林航空"],
  ["MJ", "MYW", "MyWay Airlines", "マイウェイ航空"],
  ["9D", "NMG", "Genghis Khan Airlines", "天驕航空"],
  ["5W", "WAZ", "Wizz Air Abu Dhabi", "ウィズエア・アブダビ"],
  ["KT", "KTC", "AirAsia Cambodia", "エアアジア・カンボジア"],
  ["C6", "MFX", "Centrum Air", "セントラム・エア"],
  ["TQ", "TDM", "Tandem Aero", null],
  ["VC", "VAL", "Voyageur Airways", null],
  ["Y2", "CEY", "Air Century", null],
  ["SR", "SDR", "Sundair", null],
  ["B4", "TAN", "ZanAir", "ザンエアー"],
  ["7T", "RTM", "DHL Ecuador", "アエロ・エクスプレス・デル・エクアドル"],
  ["HR", "HHN", "Hahn Air", "ハーンエア"],
  ["M2", "MZS", "Mahfooz Aviation", "マフーズ・アヴィエーション"],
  ["DA", "DAC", "Daily Air", "徳安航空"],
  ["M6", "AJT", "Amerijet International", "アメリジェット・インターナショナル"],
  ["2Q", "SNC", "Air Cargo Carriers", "エア・カーゴ・キャリアーズ"],
  ["BB", "SBS", "Seaborne Airlines", "シーボーンエアラインズ"],
  ["HN", "AJA", "Afghan Jet International", "アフガン・ジェット・インターナショナル"],
  ["9F", null, "Eurostar International", "ユーロスター・インターナショナル・リミテッド"],
  ["VP", "VQI", "FlyMe", "フライミー"],
  ["K9", "KFS", "Kalitta Charters", "カリッタ・チャーターズ"],
  ["S8", null, "SkyAir", "スカイエア"],
  ["ZO", "IZG", "ザグロス航空", "ザグロス航空"],
  ["5G", "MYI", "MAYAir", "マヤ・エア"],
  ["HJ", "TMN", "Tasman Cargo Airlines", "タスマン貨物航空"],
  ["HB", "AAQ", "Asia Atlantic Airlines", "アジア・アトランティック・エアライン"],
  ["ND", "FMI", "Fmi air", "FMI航空"],
  ["BD", "BYC", "Cambodia Bayon Airlines", "カンボジア・バイヨン航空"],
  ["S1", "SAU", "Saurya Airlines", "サユラ・エアラインズ"],
  ["RT", "BUG", "UVT Aero", "UVTエアロ"],
  ["Y6", "CIK", "AB Aviation", "ABアビエーション"],
  ["A6", "OTC", "Air Travel", "紅土航空"],
  ["2Y", "MYU", "My Indo Airlines", "マイ・インド・エアラインズ"],
  ["VV", "VPE", "Viva Air Peru", "ビバ・エア・ペルー"],
  ["RK", "RUK", "Ryanair UK", "ライアンエアー UK"],
  ["4V", "FGW", "Parata Air", "パラタ航空"],
  ["CT", "AAE", "Air Atlanta Europe", null],
  ["GV", "GUN", "Grant Aviation", null],
  ["ZS", "KZS", "Kazaviaspas", null],
  ["I4", "ISN", "Interisland Airlines", null],
  ["YQ", "LCT", "TAR México", null],
  ["XN", "MXA", "Aerolínea del Estado Mexicano (Mexicana)", null],
  ["D5", "DAE", "DHL Aero Expreso", "DHLアエロ・エクスプレッソ"],
  ["8Y", "GGE", "Ecuato Guineana", "エクアート・ギニアーナ"],
  ["RH", "RPH", "Republic Express Airlines", "リパブリック・エクスプレス航空"],
  ["W4", "WMT", "Wizz Air Malta", null],
  ["Q7", "SBM", "SkyBahamas", "スカイバハマ航空"],
  ["C7", "UZS", "Samarkand Airways", "サマルカンド航空"],
  ["NR", "NGL", "Max Air", "マックスエア"],
  ["L4", "WLB", "Wings of Lebanon", "ウィングス・オブ・レバノン"],
  ["UH", "BHL", "Bristow Helicopters", "ブリストウ・ヘリコプター"],
  ["K3", "TQN", "Taquan Air", "タカン航空"],
  ["E7", "EKA", "エクアフライト", "エクアフライト"],
  ["F2", "RCQ", "Regional Cargo", null],
  ["L2", "LYC", "Lynden Air Cargo", "リンデン・エアカーゴ"],
  ["YG", "HYT", "YTO Cargo Airlines", "YTOカーゴ・エアラインズ"],
  ["GY", "CGZ", "Colorful Guizhou Airlines", "多彩貴州航空"],
  ["4J", "FDK", "FlyDamas", "フライダマス"],
  ["T6", "ATX", "AirSWIFT", "エアスィフト"],
  ["GI", "LHA", "Air Central", "広東龍浩航空"],
  ["EX", "AVR", "Avianca Express", "アビアンカ・エクスプレス"],
  ["RF", "EOK", "Aero K", "エアロK"],
  ["BV", "TOK", "Toki Air", "トキエア"],
  ["ZN", "AZB", "Zambia Airways", null],
  ["WH", "WDL", "WDL Aviation", null],
  ["N6", "ONR", "Air One Nine Company", null],
  ["V6", "VIZ", "Aerovis Airlines", null],
  ["G2", "VXG", "Jet Express", null],
  ["3C", "DEC", "Deccan 360", null],
  ["JB", "JBA", "Helijet", null],
  ["FK", "KEW", "Keewatin Air", null],
  ["VM", "PRV", "Aerochaco", null],
  ["L8", null, "Afric Aviation", null],
  ["7M", "PAM", "MAP Linhas Aéreas", null],
  ["U5", "KRN", "Karinou Airlines", null],
  ["QM", null, "Monacair", null],
  ["2C", "CMA", "CMA CGM Air Cargo", null],
  ["9P", "FJL", "Fly Jinnah", null],
  ["HE", "HGO", "One Air", null],
  ["DI", "MBU", "Marabu Airlines", null],
  ["XE", "KEA", "Korea Express Air", "コリアエクスプレスエア"],
  ["8C", "ATN", "Air Transport International", "エア・トランスポート・インターナショナル"],
  ["YL", "LWA", "Libyan Wings", "リビアン・ウィングス"],
  ["8N", "REG", "Regional Air Services", "リージョナルエア"],
  ["RL", null, "Air Loyauté", "エア・ロアイヨーテ"],
  ["EJ", "NEA", "New England Airlines", "ニューイングランド航空"],
  ["QO", "FQA", "Quikjet Airlines", "クイックジェット・カーゴ"],
  ["GG", "KYE", "Sky Lease Cargo", "スカイリース・カーゴ"],
  ["B5", "EXZ", "East African Safari Air", "イーストアフリカン・サファリエアー"],
  ["C4", "CGK", "Click Airways", "クリック・エアウェイズ"],
  ["M5", "KEN", "Kenmore Air", "ケンモア・エア"],
  ["YR", "CVU", "Grand Canyon Airlines", null],
  ["A8", "AMF", "Ameriflight", "アメリフライト"],
  ["CQ", "CSV", "Coastal Aviation", "コースタル・アビエーション"],
  ["L3", "JOS", "DHL de Guatemala", "DHL・デ・グアテマラ"],
  ["FP", "FRE", "FlyPelican", "フライ・ペリカン"],
  ["WU", "WST", "ウェスタン航空", "ウェスタン航空"],
  ["Z4", "GZQ", "Zagrosjet", "ザグロスジェット"],
  ["XO", "SGD", "PUTANG INA KA Airways", "SEAIRインターナショナル"],
  ["O8", "RBR", "Siam Air", "サイアム・エア"],
  ["GP", "GES", "Gestair Group", null],
  ["PF", "SIF", "AirSial", "エア・シアル"],
  ["OP", "DIG", "パッションエアー", "パッションエアー"],
  ["WJ", "JES", "JetSmart Argentina", "ジェットスマート・アルゼンチン"],
  ["I9", "HLF", "Central Airlines", "中州航空"],
  ["SE", "URO", "European Cargo", "ヨーロピアン・カーゴ"],
  ["7E", "AWU", "Sylt Air", null],
  ["HK", "GAO", "Höga Kusten Flyg", null],
  ["HW", "NWL", "North-Wright Airways", null],
  ["DW", "UCR", "Aero Charter", null],
  ["9Y", null, "National Airways Ethiopia", null],
  ["3D", "APG", "Air People International", null],
  ["CH", "BMJ", "Bemidji Airlines", null],
  ["Q4", "TLK", "Starlink Aviation", null],
  ["V9", "VAA", "Van Air Europe", null],
  ["HT", "HAT", "Air Horizont", null],
  ["I7", "IIA", "Int'Air Îles", null],
  ["F5", "ATG", "Aerotranscargo", null],
  ["EG", "EUK", "Aer Lingus UK", null],
  ["9S", "UZS", "Air Samarkand", null],
  ["MN", "KGN", "Asman Airlines", null],
  ["4L", "LAU", "Líneas Aéreas Suramericanas", "リネアス・アエレアス・サーアメリカーナス"],
  ["7Q", "MNU", "Elite Airways", "エリート航空"],
  ["A7", "CFV", "CALAFIAAIRLINES", "カラフィア・エアラインズ"],
  ["EM", "CFS", "Empire Airlines", "エンパイア航空"],
  ["R0", "RPK", "Royal Airlines", "ロイヤル航空"],
  ["N9", "SHA", "Shree Airlines", "シェリー・エアラインズ"],
  ["PL", "SOA", "Southern Air Charter", "サザン・エア・チャーター"],
  ["UE", "UJC", "Ultimate Air Shuttle", "アルティメット・エアシャトル"],
  ["9X", "LTD", "Southern Airways Express", "サザン・エアウェイズ・エクスプレス"],
  ["YM", "DGB", "Air Dabia", "エア・ダビア"],
  ["DO", "SHH", "スカイ・ハイ・アビエーション・サービス", "スカイ・ハイ・アビエーション・サービス"],
  ["LT", "SNG", "LJ Air", "竜江航空"],
  ["U3", "SAY", "Sky Gates Airlines", "スカイゲーツ航空"],
  ["IC", "GOA", "Fly91", "フライ91"],
  ["5A", "AIP", "Alpine Air Express", null],
  ["IM", "MNJ", "MenaJet", null],
  ["F4", "WAF", "Air Flamenco", null],
  ["7A", "XRC", "Express Air Cargo", null],
  ["T9", "TIW", "Transcarga", null],
  ["5S", "PSV", "Servicios Aéreos Profesionales", null],
  ["Z7", "FZW", "Zimbabwe flyafrica.com", null],
  ["5Q", "HES", "Holiday Europe", null],
  ["N3", "VOS", "Volaris El Salvador", null],
  ["LI", "EZZ", "ETF Airways", null],
  ["A0", "EFW", "BA EuroFlyer", null],
  ["PP", "JAS", "Jet Aviation", "ジェット・アビエーション"],
  ["1X", null, "Branson Air Express", "ブランソン・エア・エクスプレス"],
  ["QE", "QFZ", "ファーズ・エア・ケシム", "ファーズ・エア・ケシム"],
  ["TJ", "GPD", "Tradewind Aviation", "トレードウィンド・アビエーション"],
  ["II", "CSQ", "IBC Airways", "IBCエアウェイズ"],
  ["OI", "HND", "Hinterland Aviation", "ヒンターランド航空"],
  ["SO", "SNR", "Sun Air", "サン航空 (スーダン)"],
  ["IP", "AQQ", "Apsara International Air", "アプサラ国際航空"],
  ["FC", null, "Link Airways", "リンク・エアウェイズ"],
  ["H8", "SKX", "Sky Airline Peru", "スカイ航空・ペルー"],
  ["PH", "PHA", "Phoenix Air", null],
  ["JI", "AAG", "Armenian Airlines", "アルメニアン航空"],
  ["7N", "CNA", "Centavia", null],
  ["DF", null, "Deer Jet", null],
  ["WG", "WIG", "Wiggins Airways", null],
  ["00", "ELR", "Elrom Airways", null],
  ["LF", "VTE", "Contour Airlines", null],
  ["EO", "LHN", "Express One International", null],
  ["YS", "FLZ", "Flightlink", null],
  ["1U", null, "ITA Software", null],
  ["6K", "KTC", "Kyrgyz Trans Avia", null],
  ["V4", "VES", "Vieques Air Link", null],
  ["X5", "OTJ", "Ten Airways", null],
  ["6F", "PRW", "Primera Air Nordic", null],
  ["OG", "OGN", "Originair", null],
  ["AN", "AEN", "Andorra Airlines", null],
  ["OW", "SEW", "Skyward Airlines", null],
  ["F6", "VAW", "Fly2Sky", null],
  ["MI", "FHM", "Freebird Airlines Europe", null],
  ["JK", "ACL", "AerCaribe", null],
  ["NG", "NAI", "Novair", null],
  ["UD", "UBD", "UR Airlines", null],
  ["FL", "LIL", "Fly Lili", null],
  ["H3", "HLJ", "HelloJets", null],
  ["3E", "EMU", "Sky Shuttle Helicopters", "スカイ・シャトル"],
  ["S9", "IKM", "Starbow", "スターボウ航空"],
  ["W2", "TIX", "Flexflight", "フレックスフライト"],
  ["AO", null, "Air Juan", "エア・ジュアン"],
  ["Z9", "DCP", "Delta Connection", null],
  ["FT", null, "Fly Tiwi", null],
  ["KV", "TXP", "Asian Express Airline", null],
  ["4S", "OLC", "Solar Cargo", null],
  ["LB", "BVL", "Bul Air", null],
  ["7D", null, "Madagasikara Airways", null],
  ["4A", "AMP", "Atsa Airlines", null],
  ["DU", null, "Air Liaison", null],
  ["CP", "LSI", "MSC Air", null],
  ["KK", "NGN", "Leav Aviation", null],
  ["TT", "BIX", "Braathens International Airways", null],
  ["4X", "MLH", "Avion Express Malta", null],
  ["ZU", "SAV", "Sunair", "サンエアー"],
  ["9Q", "CXE", "Caicos Express Airways", "カイコス・エクスプレス・エアウェイズ"],
  ["PS", null, "Ukraine National Airlines", null],
  ["99", null, "Solid aiR", null],
  ["1N", null, "Navitaire", null],
  ["2T", "HAM", "Haïti Ambassador Airlines", null],
  ["Y5", "ITD", "Inter Trans Avia", null],
  ["U1", null, "Videcom International", null],
  ["HI", null, "Hong Kong Air International Ltd", null],
  ["O7", "ORG", "Orenburzhye", null],
  ["J1", null, "OneJet", null],
  ["Z0", "UBT", "Norse Atlantic UK", null],
  ["IV", "GPX", "GP Aviation", null],
  ["VK", "FVJ", "ValueJet", null],
  ["H4", "HYS", "HiSky Europe", null],
  ["5L", "GAO", "Liat Air", null],
  ["U7", "UCG", "UniWorld Air Cargo", null],
  ["JG", "JDL", "Jiangsu JD Cargo Airlines", null],
  ["O9", "NOV", "Nova Airline", "ノヴァ航空"],
  ["9B", null, "AccesRail", null],
  ["G6", "BSR", "Guine Bissau Airlines", null],
  ["CR", null, "UBM Aviation", null],
  ["NB", "VZL", "Vzlet", null],
  ["H1", null, "Hahn Air Systems GmbH", null],
  ["P1", null, "Texas Sky", null],
  ["WW", null, "West Wing Aviation", null],
  ["BE", null, "Enterprise Airlines", null],
  ["4P", null, "Regional Sky", null],
  ["CO", "CNW", "North-Western Cargo International Airlines", null],
  ["K2", "TUD", "Yute Commuter Service", null],
  ["9N", "TAO", "Tropicair", null],
  ["1L", null, "CitizenPlane", null],
];
